Put benchmark boilerplate into subpackage
adrhill/SparseConnectivityTracer.jl pull request #136
Opened 2024-06-24 13:25 UTC by gdalle

Create a subpackage in `libs/SparseConnectivityTracerBenchmarks` to put:

- the Brusselator code
- the NLPModels code
- possibly the optimal power flow code in the future

This code is used by tests and benchmarks, putting it in a package dispenses us from using `include` every time. In addition, it makes it possible to import the same code in a comparison notebook like the one in https://github.com/gdalle/SparsityDetectionComparison, instead of rewriting it every time

2024-06-24 14:52 UTC, adrhill commented
Isn't that what the `benchmark` folder is for? Why don't we move everything in there and add a `Project.toml`?

2024-06-24 14:54 UTC, gdalle commented
No, the benchmark folder is for benchmarking only, and has deps like BenchmarkTools. This code is used in tests, benchmarks and other places too. And it needs to be in a package to be importable in e.g. a Pluto notebook (to which I can give the exact GitHub URL of `libs/SparseConnectivityTracerBenchmarks`)

2024-06-24 14:59 UTC, gdalle commented
The name may be ill-chosen, perhaps `SparseConnectivityTracerProblems` would be better?

2024-06-24 14:59 UTC, adrhill commented
> No, the benchmark folder is for benchmarking only

Not trying to be snarky here, but isn't `libs/SparseConnectivityTracerBenchmarks` also about benchmarking?

> and has deps like BenchmarkTools

Is that a big issue? I think removing some complexity at the cost of one dependency is acceptable.

> to which I can give the exact GitHub URL of `libs/SparseConnectivityTracerBenchmarks`)

Wouldn't `benchmark` be a URL that's just as viable?

2024-06-24 15:00 UTC, adrhill commented
At the very least, we could move this into `benchmarks/libs/SparseConnectivityTracerBenchmarks` if this somehow is necessary for Pluto.

2024-06-24 15:03 UTC, gdalle commented
> Not trying to be snarky here, but isn't libs/SparseConnectivityTracerBenchmarks also about benchmarking?

See my latest comment, here I meant "benchmarks" in the sense of "benchmark instance definitions", not "full specification of a benchmark suite with sizes and evals and so on". Hence the possibility of an alternative name like `SparseConnectivityTracerProblems` or `SparseConnectivityTracerInstances`.

2024-06-24 15:04 UTC, gdalle commented
> Is that a big issue? I think removing some complexity at the cost of one dependency is acceptable.

This is pretty much a constant-complexity PR. It's just replacing the `include` with a `using`

> Wouldn't benchmark be a URL that's just as viable?

It's not just about giving a URL, it's about giving the URL of a package (as opposed to including a file)

2024-06-25 15:22 UTC, adrhill requested changes

2024-06-25 15:22 UTC, adrhill commented on test/nlpmodels.jl
> +@testset "$name" for name in Symbol.(OptimizationProblems.meta[!, :name])
Maybe `problem_names` could be exported from `SparseConnectivityTracerBenchmarks` as well?

2024-06-25 15:22 UTC, adrhill commented on test/Project.toml
> +SimpleDiffEq = "05bca326-078c-5bf0-a5bf-ce7c7982d7fd"
Why did this have to be added?

2024-06-25 15:22 UTC, adrhill commented on benchmark/benchmarks.jl
> +@jog SparseConnectivityTracer
This confused me at first and I had to refer to the PkgJogger docs.
Could you add a comment, e.g. *"Use `PkgJogger.@jog` to create the JogSparseConnectivityTracer package"*?

2024-06-25 15:22 UTC, adrhill commented on benchmark/SparseConnectivityTracerBenchmarks/src/nlpmodels.jl
> -problem_names() = Symbol.(OptimizationProblems.meta[!, :name])
Can this be kept and exported?

2024-06-25 15:50 UTC, gdalle commented on test/Project.toml
> +SimpleDiffEq = "05bca326-078c-5bf0-a5bf-ce7c7982d7fd"
because it's used in the benchmarks

2024-06-26 07:27 UTC, gdalle commented
@adrhill the benchmarks work on this PR branch and fail on main but that's expected, this is good to merge

2024-06-26 09:46 UTC, merged